### ISSUE TITLE
fails on .xlsx file in subdir

### ISSUE THREAD

**Issue by pvbemmelen62** [pvbemmelen62/search-xlsx-for-word#1]
```

Paul@livingroom-pc /cygdrive/g/paul/excel
$ find . -name "*.xlsx" -print
./mama.xlsx
./papa.xlsx
./subdir/mama.xlsx
./Voorbeeldtemplate Paul Leges.xlsx
./Voorbeeldtemplate-Paul-Leges.xlsx

Paul@livingroom-pc /cygdrive/g/paul/excel
$ ./*.sh --word id papa.xlsx subdir/mama.xlsx
papa.xlsx
    <t>id:referenceDate</t>
    <t>id:Temp_LegesTarief</t>
    <t>id:Temp_LegesVanToepassing</t>
    <t>id:SubsidieActief</t>
    <t>Temp_TariefSubsidieActief</t>
    <t>"Subsidie"</t>
    <t>Hoog en Subsidie</t>
    <t>in:Subsidie actief</t>
subdir/mama.xlsx
cp: cannot create regular file 'tmp/subdir/mama.xlsx.jar': No such file or directory
java.io.FileNotFoundException: subdir\mama.xlsx.jar (The system cannot find the path specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
        at jdk.jartool/sun.tools.jar.Main.run(Main.java:407)
        at jdk.jartool/sun.tools.jar.Main.main(Main.java:1676)
cat: xl/sharedStrings.xml: No such file or directory
-:1: parser error : Document is empty

^

Paul@livingroom-pc /cygdrive/g/paul/excel
$

```

**Comment by pvbemmelen62** [comment]
Solved in commit  fa2062f .
